### ISSUE TITLE
[BUG] Notebooks does not obey Date Format

### ISSUE THREAD

**Issue by stockholmux** [opensearch-project/trace-analytics#250]
**Describe the bug**
If you change the date format in Stack Management > Advanced Settings > Date Format, Notebooks still renders the date in the `MM/DD/YYYY` format. 

**To Reproduce**
1. Go to Stack Management > Advanced Settings > Date Format and change the date format to something different. I used `DD MMM, YYYY @ HH:mm:ss.SSS`
2. Go back to notebooks and create a notebook - I added a visualization. 
3. The visualization timestamp is still in MM/DD/YYYY format

**Expected behavior**
Notebooks would follow the the date format.

**Plugins**
All standard

**Screenshots**

Setting:
<img width="1193" alt="Screen Shot 2021-09-09 at 11 02 05 AM" src="https://user-images.githubusercontent.com/1152927/132730416-15a4620a-3623-425b-a8f6-7d8e1413159d.png">

Notebooks:
<img width="453" alt="Screen Shot 2021-09-09 at 11 03 08 AM" src="https://user-images.githubusercontent.com/1152927/132730484-dc319485-88e5-43f4-a84c-7938c01ad75c.png">

Discover tab correctly showing date format:
<img width="585" alt="Screen Shot 2021-09-09 at 11 04 12 AM" src="https://user-images.githubusercontent.com/1152927/132730650-5a7fc43c-c97f-4a37-9284-f1ebb2768f41.png">

**Host/Environment (please complete the following information):**
 - OS: macos
 - chrome

forum thread: https://discuss.opendistrocommunity.dev/t/opensearch-notebooks-date-format/6919/5

**Comment by stboissdev** [comment]
this bug are on other opensearch plugin:
Alerting : 
![image](https://user-images.githubusercontent.com/24654609/144404837-627434f5-61aa-4c6c-8551-f7088e90ed16.png)
![image](https://user-images.githubusercontent.com/24654609/144404898-dd5231e1-0d7b-4e56-be61-f9dc839dbf25.png)
![image](https://user-images.githubusercontent.com/24654609/144404959-2377bfd9-25d5-4cf1-b94d-df626c492c5a.png)
Notebooks : 
![image](https://user-images.githubusercontent.com/24654609/144405156-76a62aec-afcf-4526-9331-eef72ad67ca5.png)
Anomaly detection : 
![image](https://user-images.githubusercontent.com/24654609/144405352-05903bbb-02a2-4f69-a92a-f05d13c1c185.png)
![image](https://user-images.githubusercontent.com/24654609/144405419-c57ba06b-f5f7-4442-9c77-c1db50ff43ed.png)
Index Management : 
![image](https://user-images.githubusercontent.com/24654609/144405576-01177f14-9b09-43b1-9e9d-ede2f07484cd.png)

**Comment by stockholmux** [comment]
@stboissdev What is your date format?

**Comment by joshuali925** [comment]
We purposely chose a time format up to minutes for created/update, because the advanced settings date format is usually precise which might not be useful in this context. I'll keep it for now unless there is an objection, but I can take a look for the visualization time format
