### ISSUE TITLE
[BUG] detailed trace window is not opening on the timeline view

### ISSUE THREAD

**Issue by arnitolog** [opensearch-project/trace-analytics#275]
**Describe the bug**
detailed trace window is not opening on the timeline view

**To Reproduce**
1. Go to Observability/Trace analytics/Traces/any tace
2. switch to timeline view
3. Click on any bar in the spans section

**Expected behavior**
the detailed side window is opening on the span click. the same as for `spanID` click on the `Span list` view

**Plugins**
all standard OpenSearch plugins

**Screenshots**
not working on the `Timeline` view
![image](https://user-images.githubusercontent.com/34036079/143251932-6bf0f8e2-a720-45f5-94f6-59464e86d388.png)
working on the `Span list`
![image](https://user-images.githubusercontent.com/34036079/143251984-176b9982-4f31-4b86-b603-b8caf3eedc9f.png)

**Host/Environment (please complete the following information):**
 - Version 1.2.0

**Additional context**

**Comment by joshuali925** [comment]
thanks for reporting this. looks like the plot onclick handler got (accidentally?) removed in f1d351276972b41368c0bef3f4e2736ab910fb21. will confirm and add it back

**Comment by arnitolog** [comment]
@joshuali925 have you had a chance to look at/fix that bug? It is a very useful feature and I really want to have it in my current installation

**Comment by joshuali925** [comment]
Hi @arnitolog, I added a PR that will fix this. It will be released in next version which might take a while, but you can follow these steps to update your current installation:

1. download `dashboards-observability.zip` from "artifacts" section in https://github.com/opensearch-project/trace-analytics/actions/runs/1536466363
2. run `unzip dashboards-observability.zip` once and you should get `dashboards-observability-1.2.0.0.zip`
3. go to dashboards directory, run `./bin/opensearch-dashboards-plugin remove observabilityDashboards`
4. run `./bin/opensearch-dashboards-plugin install file://<absolute-path-to-dashboards-observability-1.2.0.0.zip>`
5. restart opensearch dashboards

Let me know if you face any issues

**Comment by arnitolog** [comment]
thank you @joshuali925 it works for me.

**Comment by joshuali925** [comment]
sure. closing this
