### ISSUE TITLE
Add backwards compatibility tests for automation

### ISSUE THREAD

**Issue by kavithacm** [opensearch-project/trace-analytics#276]
Add backwards compatibility tests for the plugin to automate end-to-end upgrade paths for faster releases. Developer documentation for implementing bwc tests and hooking them to CI: https://github.com/opensearch-project/opensearch-plugins/blob/main/TESTING.md#backwards-compatibility-testing

**Comment by anirudha** [comment]
testing bwc 
notebooks 1.1/1.0 -> 1.2 
1.2 -> 1.3
