### ISSUE TITLE
Observability : Event Analytics - Visualizations

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/trace-analytics#53]
**Is your feature request related to a problem? Please describe.**
Add Charting support to PPL and event analytics

<img width="916" alt="Screen Shot 2021-08-09 at 9 50 03 AM" src="https://user-images.githubusercontent.com/19362/128743524-96a5f7b4-27d5-4fd1-aedb-f852124a61e4.png">
<img width="765" alt="Screen Shot 2021-08-09 at 9 50 46 AM" src="https://user-images.githubusercontent.com/19362/128743634-3dd6492d-4b1c-4e45-8600-f18a5a95ae69.png">

**Describe the solution you'd like**
Top 3 most popular charts in chart tab.

**Comment by anirudha** [comment]
https://user-images.githubusercontent.com/19362/137158907-bf5814ae-59d3-4f61-8ecf-649f49c17560.mov
