### ISSUE TITLE
New Observability Plugin

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/trace-analytics#63]
### Observability: Logs, Metrics APM & Trace Analytics

Software is becoming exponentially more complicated; from monoliths, micro services application are built with many languages, frameworks, serverless functions, data stores and more. This makes it difficult to understand problems when problems do arise. To stay competitive developers are deploying code faster and increasing complexity to maintain and debug.  This has resulted in an increase in complex telemetry. This why we will build “The Observability plugin framework” to provide end-to-end visibility into performance and code efficiency. 

**Why OpenSearch ?**
OpenSearch's Lucene data structures are one the most valuable assets for us that can be used to store structured or unstructured data for text analysis, relevance search, clustering and anomaly detection. It can also store numerical data points efficiently while allowing operation that can bucket, sort, aggregate and run correlation operations. Lucene can also supports graph, geospatial and semantic operations on the  same datasets. All this while being able to scale to large data volumes.

Our goal is to offer a complete solution for log analytics, trace analytics  and metrics analysis built around the core principles as follows. 

1/ **Open instrumentation** 
Support for top public agents for logs, metrics and traces. 
Open telemetry is a good standard, and the Data Prepper project will be used to support that an add support for enrichment over it. Observability platform will define the Physical OpenSearch Simple Schema (OS3) mapping patterns and relationships. 

Every data source will use an index which follows its own usage of OS3. For example EC2 data will be stored in an machine specific index with the relevant fields from OS3. A single OpenSearch instance can contain multiple indices each containing a data source integrations storing values for its own data in the OS3 format. 

2/ **Connected entities**
Relationships and correlations are keys to unlocking value in machine data. Observability platform will map OpenSearch indices with relationships, thus allowing data exploration and deeper relational analytics. For example, the host and CPU field in an EC2 index have a relationship to a host and CPU field in micro services. As we analyze the host for issues we can use our relational links to quickly overlay different application micro services and  all processes running on the same host to analyze them in an unified view. 

3/ **Programmability**
 Every business problem is unique, application needs keep changing with the development life-cycle. To support custom and specialized application simultaneously, we will use reusable components as Operational Panels and plugins to allow for extensibility. All workflows and UIs will be built on Piped Processing Language (PPL) with composable UI elements.

**Observability Deliverables** 
- Event explorer #41
- Add auto-suggest for Piped Processing Language #42 
- Visualization editor #53
- Custom Operational panels #67
- Trace Analytics integration 
- Enable Log , Trace correlation #86
- Support for saved queries and saved charts #85
- Enable support for OpenSearch Simple Schema #25
- App Analytics Dashboards
- Create plugin panels for Query Tabs, Query view sub-tabs , co-relation fly-outs

**Comment by juergen-walter** [comment]
Hi @anirudha, will "The Observability plugin framework” you announce be an extension of the trace-analytics plugin or evolve into a separate project?

**Comment by anirudha** [comment]
Trace analytics will be an observability child project. 


The trace analytics repo will be renamed observability. The current code will evolve without breaking compatibility for older trace-analytics users

**Comment by louzadod** [comment]
Cool. The log tailing feature #768 fits into the Observability umbrella.

**Comment by elfisher** [comment]
> Cool. The log tailing feature #768 fits into the Observability umbrella.

@anirudha is the idea to include the tailing feature in the event explorer UI as a toggle?
