### ISSUE TITLE
Observability - Add redux and react-redux to manage app states

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/trace-analytics#66]
**Is your feature request related to a problem? Please describe.**
With more modules being developed, the state management and sharing data among different parts of the app is becoming more and more complex and trivial.

**Describe the solution you'd like**
It needs to have a solution to manage all the states from front end side. 
Redux + react-redux

**Describe alternatives you've considered**
Flux, mobx

**Comment by joshuali925** [comment]
i thought the new usecontext and usereducer hooks can solve most of what redux solves, is it necessary to add redux? I'm thinking about effort needed to refactor trace analytics

**Comment by mengweieric** [comment]
There are some considerations on why I tend to use redux + react-redux in favor of native useContext combined with useReducer. The observability app is going to be a big app with data sharing and state mutating across different modules and components. Although the native way for sure would handle most of the situations well, but in order to handle those things with native way, we sometimes need to invent the wheel like provide our own way to combine reducers, batch send if we want to trigger multiple state-changing events, maybe add existing or custom middleware, or many others. All of which redux and react-redux have already provided out of the box APIs. I'm thinking that by using redux and react-redux, the team may align our ways and save some effort when dealing with state management development.
 
As for the refactoring effort, currently I'm not sure how exactly the trace analytics would interact with other modules and how it would be integrated with the observability app as a whole. If it does not need data from other modules and works fine with its own state data after integration, then maybe no immediate refactoring adopting redux is actually needed. If it does then I think it depends on what are the future goals of this app. Do we keep adding more modules, functionalities and components that need more complex state management logic? Or does the app stay pretty much what it is right now and does not need too much data sharing now and in the future? If it is the latter situation and it takes too much effort to refactor trace analytics, then I’d not recommend adopting redux.

**Comment by joshuali925** [comment]
got it, thanks for the explanation. in that case I agree it would be easier to use redux. trace analytics won't be sharing many states with observability when initially merged together, and when we extend trace analytics and observability with more features it would be easier to refactor trace analytics if the state management is straightforward in observability. I remember seeing other plugins in opensearch dashboards that also use redux, so we should be good

**Comment by mengweieric** [comment]
Yes, the redux and react-redux has already been installed and referenced by other plugin(s). We can directly import it without having to install in our own plugin.
