### ISSUE TITLE
Observability :  Operational Panels

### ISSUE THREAD

**Issue by ps48** [opensearch-project/trace-analytics#67]
## Summary

Custom Observability Panels provide users with the ability to save different visualizations on ingested observability data.

### Home Page

1. Enable users to view saved custom observability panels.
2. Users should be able to Create/Rename/Duplicate/Delete custom dashboards.

### Custom Panel Page

1. Enable users to add an existing/new visualization to the custom panel.
2. Enable users to add a new visualization using PPL query with a visualization preview area. 
3. Enable users to select different visualization charts like line, bar or pie. 
4. Enable users with advance visualization options by redirecting them to event explorer page, for adding new visualization. 
5. Enable users to add multiple visualizations with options of rearrangement and ability to move visualizations in a panel. 
6. Enable users to query and filter the visualizations on a panel with PPL commands. 

**How are they different from existing Dashboards?**

1. Custom Observability Panels work on ingested observability data.
2. PPL is used as the default language for querying and filtering instead of DQL.

**Comment by arulselvan** [comment]
@anirudha, thanks for the great explanation, is there any way to export and import this operation panel and visualizations?
