### ISSUE TITLE
[ENHANCEMENT]: Updating Visualizations Preview functionality

### ISSUE THREAD

**Issue by pratibhapandey16** [opensearch-project/trace-analytics#826]
Visualization should reload to reflect changes immediately whenever any changes are made, without user clicking on `Preview` button.

**Comment by mrunal-z** [comment]
Hi @mengweieric @btzeng @anirudha,

Following is the demo for this enhancement, shown using line chart -
https://user-images.githubusercontent.com/79525611/177828709-36f56108-dbc9-49cb-bfa6-2896eaf097bf.mp4


We've removed the 'Preview' and 'Update Chart' buttons from config panel and data configurations. Also, if the user clicks on the 'x' button in any of the data configurations fields, the chart shows 'no results found' until the user selects a proper value, let me know if that seems like the right implementation to you.

Thanks!
